### PR TITLE
Fix union in header query issue

### LINKED ISSUE #2185: Named Union Type Not Emitted In Generated Code
For Schema Registry generation, the union type `SchemaContentTypeValues` is not emitted. The TypeSpec definition for the `SchemaContentTypeValues` is [here](https://github.com/Azure/azure-rest-api-specs/blob/496ef847bd63aab7c10b2225701b125ff161ea05/specification/schemaregistry/SchemaRegistry/main.tsp#L133C1-L142C1)
```
union SchemaContentTypeValues {
  avro: "application/json; serialization=Avro",
  @added(ServiceApiVersions.V2022_10)
  json: "application/json; serialization=json",
  @added(ServiceApiVersions.V2022_10)
  custom: "text/plain; charset=utf-8",
  @added(ServiceApiVersions.V2023_07_01)
  protobuf: "text/vnd.ms.protobuf",
}
```

In the [generated file](https://github.com/minhanh-phan/azure-sdk-for-js/blob/490c9850d0837f86c697d872743dec60aa44007e/sdk/schemaregistry/schema-registry/sources/generated/src/parameters.ts#L24C1-L28C1), we have the following generated definition.
```ts
export interface RegisterSchemaMediaTypesParam {
  /** The content type for given schema. */
  contentType: SchemaContentTypeValuesOutput;
}
```
The type `SchemaContentTypeValuesOutput` does not exist anywhere in the generated output, so we have the following error
```
sources/generated/src/responses.ts(92,19): error TS2304: Cannot find name 'SchemaContentTypeValuesOutput'.
```
To reproduce: Use the latest commit from [this PR](https://github.com/Azure/azure-rest-api-specs/pull/25168/files#diff-1b5581b266947b270ea1249cc8c8763c9fc4a7e24b6e01182d84f07241795ee8), commit `496ef847bd63aab7c10b2225701b125ff161ea05`.

### PR DESCRIPTION
**Pull request by qiaozha**
fixes #2185

### CODE REVIEW

File: packages/typespec-ts/src/transform/transformResponses.ts [hunk 1]
```diff
@@ -141,6 +142,9 @@ function transformHeaders(
         SchemaContext.Output
       ]) as Schema;
       const type = getTypeName(typeSchema);
+      if (typeSchema.type === "object" && typeSchema.enum) {
```
Comment (joheredi) [inline packages/typespec-ts/src/transform/transformResponses.ts:145]: I wonder it it would be helpful to create a helper util to check if the schema has an enum

**Review by joheredi — APPROVED** [review]

**Comment by qiaozha** [comment]
Hold this PR as there's some issues in the modular layer.

File: packages/typespec-ts/src/utils/modelUtils.ts [hunk 2]
```diff
@@ -1197,6 +1197,30 @@ export function getTypeName(schema: Schema, usage?: SchemaContext[]): string {
...
+  const formattedName = typeName.replace("Date | string", "string");
+  const allTypes = formattedName.includes(" | ")
+    ? formattedName.split(" | ")
+    : formattedName.split("|");
+  const canSerialize = allTypes.every((type) => {
+    return (
+      ["string", "number", "boolean"].includes(type) ||
+      (type.startsWith('"') && type.endsWith('"')) ||
+      /^[0-9]*$/.test(type) ||
+      ["true", "false"].includes(type) ||
```
Comment (MaryGao) [inline packages/typespec-ts/src/utils/modelUtils.ts:1214]: I was wondering if we could leverage the isConstant to identify the literal values. Because identifying the literal type is error prone e.g do we consider negative number or float? do we consider the single quote string or three quote strings?

https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-ts/test/unit/transform/transformSchemas.spec.ts#L77-L168

File: packages/typespec-ts/src/utils/modelUtils.ts [hunk 3]
```diff
@@ -1197,6 +1197,30 @@ export function getTypeName(schema: Schema, usage?: SchemaContext[]): string {
...
+      ["null"].includes(type)
```
Comment (MaryGao) [inline packages/typespec-ts/src/utils/modelUtils.ts:1215]: I remember currently the null value is not allowed in core for headers.

File: packages/typespec-ts/src/transform/transformResponses.ts (hunk 1 above)
Comment (MaryGao) [inline packages/typespec-ts/src/transform/transformResponses.ts:145]: Can we use the getImportedModelName instead?

https://github.com/Azure/autorest.typescript/pull/2155/files#diff-71234ca40517891bd095b50338b2302c0fc737b72d7514989d13521ae67475d4R144-R147

File: packages/typespec-ts/src/transform/transformParameters.ts [hunk 4]
```diff
@@ -163,6 +170,11 @@ function getParameterMetadata(
       }`;
     }
   }
+  type =
+    paramType !== "query" ? getSerializeTypeName(schema, schemaContext) : type;
+  if (schema.type === "object" && schema.enum) {
```
Comment (MaryGao) [inline packages/typespec-ts/src/transform/transformParameters.ts:175]: Can we use the getImportedModelName instead?

File: packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts [hunk 5]
```diff
@@ -1320,4 +1316,389 @@ describe("inheritance & polymorphism", () => {
...
+        export type SchemaContentTypeValues =
+          | "application/json; serialization=Avro"
+          | "application/json; serialization=json"
+          | "text/plain; charset=utf-8"
+          | "text/vnd.ms.protobuf";
+        `
+      );
+    });
+
+    it("extensible enums with string literals being used in regular headers", async () => {
```
Comment (qiaozha) [inline packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1462]:
```suggestion
    it.skip("extensible enums with string literals being used in regular headers", async () => {
```

File: packages/typespec-ts/src/transform/transformResponses.ts (hunk 1 above)
Comment (qiaozha) [reply packages/typespec-ts/src/transform/transformResponses.ts]: updated.

File: packages/typespec-ts/src/utils/modelUtils.ts (hunk 2 above)
Comment (qiaozha) [reply packages/typespec-ts/src/utils/modelUtils.ts:1217]: I am using !isNaN(Number(type)) to determine if it's a number now. We probably can't use isConstant as the schema is an union, and we

File: packages/typespec-ts/src/utils/modelUtils.ts (hunk 3 above)
Comment (qiaozha) [reply packages/typespec-ts/src/utils/modelUtils.ts]: https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-test/test/widget_dpg/generated/typespec-ts/src/rest/parameters.ts#L18 I may have lost some context, is this not working ?

File: packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts [hunk 6]
```diff
@@ -1320,4 +1316,389 @@ describe("inheritance & polymorphism", () => {
...
+        export type SchemaContentTypeValues =
+          | "application/json; serialization=Avro"
+          | "application/json; serialization=json"
+          | "text/plain; charset=utf-8"
+          | "text/vnd.ms.protobuf";
+        `
+      );
+    });
+
+    it.skip("extensible enums with string literals being used in regular headers", async () => {
```
Comment (qiaozha) [inline packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1462]: skip this test as we haven't supported enums in modular yet.

**Comment by qiaozha** [comment]
Moving the isKey readOnly logic fix and support named union in Modular layer into this PR.

File: packages/typespec-ts/src/utils/operationUtil.ts [hunk 7]
```diff
@@ -179,17 +179,22 @@ export function isDefinedStatusCode(statusCodes: HttpStatusCodesEntry) {
...
-    isByteOrByteUnion(dpgContext, body)
-  ) {
-    return true;
+  const allContentTypes = Array.isArray(contentType)
+    ? contentType
+    : [contentType];
+  for (const type of allContentTypes) {
+    const contentType = `"${type}"`;
+    if (
+      contentType !== `"application/json"` &&
```
[the remark this answers is not in the document]
Comment (qiaozha) [reply packages/typespec-ts/src/utils/operationUtil.ts:190]: Create an issue here https://github.com/Azure/autorest.typescript/issues/2200

**Review by lirenhe — APPROVED** [review]

File: packages/typespec-ts/src/modular/emitModels.ts [hunk 8]
```diff
@@ -53,7 +53,8 @@ function extractModels(codeModel: ModularCodeModel): Type[] {
 
 export function extractAliases(codeModel: ModularCodeModel): Type[] {
   const models = codeModel.types.filter(
-    (t) => t.type === "model" && t.alias && t.aliasType
+    (t) =>
+      (t.type === "model" || t.type === "combined") && t.alias && t.aliasType
```
Comment (MaryGao) [inline packages/typespec-ts/src/modular/emitModels.ts:57]: Could you add a comment for `model`? It is for base model, right?

**Review by MaryGao — APPROVED** [review]
LGTM

File: packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts [hunk 9]
```diff
@@ -1320,4 +1316,389 @@ describe("inheritance & polymorphism", () => {
       `
     );
   });
+
+  describe("should generate models for header parameters", () => {
+    it("union variants with string literals being used in contentType headers", async () => {
```
Comment (MaryGao) [inline packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1321]: Do we have a case for response header with named union?

File: packages/typespec-ts/test/unit/transform/transformSchemas.spec.ts [hunk 10]
```diff
@@ -257,11 +268,22 @@ describe("#transformSchemas", () => {
...
       assert.isNotNull(property);
       assert.deepEqual(property, {
-        type: '"English"|"Chinese"',
+        type: '"English" | "Chinese"',
         name: "string",
         typeName: "string",
-        description: "Possible values: English, Chinese",
-        enum: ["English", "Chinese"],
+        description: "Possible values: \"English\", \"Chinese\"",
+        enum: [
```
Comment (MaryGao) [inline packages/typespec-ts/test/unit/transform/transformSchemas.spec.ts:275]: Not sure this change would impact the mock sample gen or not?

File: packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts [hunk 11]
```diff
@@ -1320,4 +1316,389 @@ describe("inheritance & polymorphism", () => {
...
+        ): Promise<void> {
+          const result = await _getSend(context, contentType, body, options);
+          return _getDeserialize(result);
+        }
+        `,
+        true
+      );
+    });
+
+    it("union variants with string literals being used in regular headers", async () => {
```
[the remark this answers is not in the document]
Comment (qiaozha) [reply packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts]: updated.

File: packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts (hunk 9 above)
Comment (qiaozha) [reply packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1321]: updated.

File: packages/typespec-ts/test/unit/transform/transformSchemas.spec.ts (hunk 10 above)
Comment (qiaozha) [reply packages/typespec-ts/test/unit/transform/transformSchemas.spec.ts:275]: I don't think so, we have both ut and smoke-test for mock sample gen, and they are fine.  https://github.com/Azure/autorest.typescript/pull/2189/files#diff-e83f5c92c1dffc0b39a10e7bd9ecb3623b13e6be14273e3af761cd72390f139bL92-R92

File: packages/typespec-ts/src/modular/emitModels.ts (hunk 8 above)
Comment (qiaozha) [reply packages/typespec-ts/src/modular/emitModels.ts:62]: added.

File: packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts [hunk 12]
```diff
@@ -1320,4 +1316,466 @@ describe("inheritance & polymorphism", () => {
...
+            throw createRestError(result);
+          }
+          return;
+        }
+        export async function get(
+          context: Client,
+          testHeader: "A" | "B",
+          body: string,
+          options: GetOptions = { requestOptions: {} },
+        ): Promise<void> {
```
Comment (qiaozha) [inline packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1530]: In this case, we actually have response headers returne, but we just returned void in the modular layer, I wonder if we should rethink about this a little ? @xirzec @joheredi

Comment (qiaozha) [reply packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1530]: here's the typespec
```
      op get(
        @header("test-header") testHeader: "A" | "B",
        @body body: string,
      ): { @header("test-header") testHeader: "A" | "B" };
```

Comment (qiaozha) [reply packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts:1530]: create an issue https://github.com/Azure/autorest.typescript/issues/2202 to track this.

**Comment by qiaozha** [comment]
We can fix remaining issue in other PRs.
