### PR TITLE
try-fix-doc-in-params-tag

### LINKED ISSUE #1821: Issues #4: CADL Generated Code Issue in EventGrid SDK
While working on the EventGrid SDK, generated from CADL files, I have noticed the following. The linter is reporting several errors for the following error: `@typescript-eslint/naming-convention`.

In addition to that, there is another linter issue also. The method documentation is in the following formar:

```
/**
 * Initialize a new instance of `AzureMessagingEventGridClient`
 * @param endpoint type: string, The host name of the namespace, e.g. namespaceName1.westus-1.eventgrid.azure.net
 * @param credentials type: TokenCredential|KeyCredential, uniquely identify client credential
 * @param options type: ClientOptions, the parameter for all optional parameters
 */
```

This format causes issue with the linter and reports error `tsdoc-param-tag-missing-hyphen` for the rule `tsdoc/syntax`. It should be in the following format:

```
/**
 * Initialize a new instance of `AzureMessagingEventGridClient`
 * @param endpoint - The host name of the namespace, e.g. namespaceName1.westus-1.eventgrid.azure.net
 * @param credentials - uniquely identify client credential
 * @param options - the parameter for all optional parameters
 */
```

Please fix the above issues. 

@joheredi @xirzec FYI.....

### PR DESCRIPTION
**Pull request by qiaozha**
fixes #1821

### CODE REVIEW

File: packages/autorest.typescript/test/rlcIntegration/generated/bodyComplexRest/src/bodyComplexRestClient.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { BodyComplexRestClient } from "./clientDefinitions";
 
 /**
  * Initialize a new instance of `BodyComplexRestClient`
- * @param options type: ClientOptions, the parameter for all optional parameters
+ * @param options - the parameter for all optional parameters
```
Comment (MaryGao) [inline packages/autorest.typescript/test/rlcIntegration/generated/bodyComplexRest/src/bodyComplexRestClient.ts:10]: @qiaozha @joheredi Do you think we could add the `@typescript-eslint/naming-convention` validation in our build?

Comment (qiaozha) [reply packages/autorest.typescript/test/rlcIntegration/generated/bodyComplexRest/src/bodyComplexRestClient.ts:10]: at least not for rest level client, they will easily break this rule .

File: packages/autorest.typescript/test/commands/smoke-test-list.ts [hunk 2]
```diff
@@ -46,133 +46,133 @@ const getArmReadmes = (): SpecDefinition[] => {
...
-  //   params: [
-  //     AutorestParams.ModelDedup,
-  //     AutorestParams.GenerateTest,
-  //     AutorestParams.GenerateSamples,
-  //     AutorestParams.AzureSdkForJs
-  //   ],
-  //   branch: "925e8285703ddd461588d8f5fbf14bd97c286fab",
-  //   buildTag: "ci_3"
-  // },
+  ...getArmReadmes(),
```
Comment (qiaozha) [inline packages/autorest.typescript/test/commands/smoke-test-list.ts:49]: Can we get this merged, those test case are comment out by accident.

**Review by MaryGao — APPROVED** [review]
